apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.appName}}-pv
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{.Values.appName}}
    app.kubernetes.io/version: {{ quote .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    some.label.io/who-knows: {{ .Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /var/syncthing
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - {{.Values.appName}}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
