apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.appName}}-pvc
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{.Values.appName}}
    app.kubernetes.io/version: {{ quote .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    some.label.io/who-knows: {{ .Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.appName}}
