apiVersion: v1
kind: Service
metadata:
  name: syncthing-http
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: syncthing
  ports:
  - name: https
    port: 443
    targetPort: http
  - name: http
    port: 80
    targetPort: http