apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-persistent-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/raynaldm/syncthing/data
  persistentVolumeReclaimPolicy: Recycle
