apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
