apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-pv
  labels:
    app.kubernetes.io/name: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /var/syncthing
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - syncthing
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
