apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing